### ISSUE TITLE
OnDragComplete Functionality 

### ISSUE THREAD

**Issue by iSukhi** [codechem/CC.CircularSlider.Forms#2]
As I am dragging the thumb on this slider the OnValueChanged Function is called multiple times. Like a normal slider does this support OnDragCOmplete?

**Comment by iboshkov** [comment]
Hi @iSukhi that sounds reasonable, added the event to the control, please try the sample in the branch `feature/dragend-event`

Let me know if it works okay, from my testing seems okay.
