### ISSUE TITLE
1.0.11 does not exist in nuget repo. How to update?

### ISSUE THREAD

**Issue by GrullonD** [codechem/CC.CircularSlider.Forms#4]
I'm trying to update from 1.0.10 to 1.0.11 but this does not exist in the nuget website. https://www.nuget.org/packages/CC.CircularSlider.Forms/ shows 1.0.10 being the latest. How do we update to 1.0.11? 

The new drag feature would help disable ScrollView scrolling when trying to change the slider value.

**Comment by iboshkov** [comment]
Sorry about that, can you try again?

**Comment by iboshkov** [comment]
Try updating to 1.0.13 now, there's an additional fix in there. Let me know if you find any issues.
